"""tags to json

Revision ID: c7addad52c72
Revises: f691dd06f727
Create Date: 2024-10-10 19:23:14.992401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7addad52c72'
down_revision = 'f691dd06f727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
                postgresql_using='tags::json',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               postgresql_using='tags::text',
               existing_nullable=False)

    # ### end Alembic commands ###
